server:
  port: 8761 # le port par defaut d'eureka
eureka:
  client: # cette section configure eureka client
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka-service