spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  application:
    name: kafkaProducer-services # le nom qui s'affichera sur le dashboard d'eurika
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # quelle serveur d'eurika cette application doit suivre donner l'url (on peut avoir plusieur serveur d'eurika)

server:
  port: 0